manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
    - name: englmaxi
      url-base: https://github.com/englmaxi/
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: zmk-config
      remote: englmaxi
      revision: master
  self:
    path: config
